osx_image: xcode9.4
language: swift
script:
  - set -o pipefail; xcodebuild test -workspace 'Brisk iOS.xcworkspace' -scheme Brisk -sdk iphonesimulator11.4 -destination 'name=iPhone SE,OS=11.4' ONLY_ACTIVE_ARCH=NO | xcpretty 