osx_image: xcode9.4
language: swift
before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod install
script:
  - set -o pipefail
  - xcodebuild test -workspace 'Brisk iOS.xcworkspace' -scheme Brisk -sdk iphonesimulator11.4 -destination 'name=iPhone SE,OS=11.4' ONLY_ACTIVE_ARCH=NO | xcpretty